name: CI
on:
  push:
    branches:
      - devel
      - main
      - master
      - RELEASE_*
  pull_request:
    branches:
      - devel
      - main
      - master
      - RELEASE_*

jobs:
  bioccheck:
    uses: bioconductor/workflows/.github/workflows/bioccheck.yml@v1
    with:
      enable_pkgdown: true
      error_on: warning
    permissions:
      pages: write
      id-token: write

